name: lobehub
services:
  qstash:
    image: public.ecr.aws/upstash/qstash:latest
    container_name: lobe-qstash
    command: qstash dev
    environment:
      - QSTASH_DEV_PORT=8080
    restart: always
    networks:
      - lobe-network

networks:
  lobe-network:
    driver: bridge
